- tz.cpp
- tz.h
Replace my accidental use of NULL with nullptr.
Improve some comments.
> Throw a runtime error if the install folder does not exist.

- tz.cpp
> Fixed GCC 4.8 compilation issue

- date.h
> Vs2013 integration

- tz.cpp
- tz.h
- tz_private.h
> TZ stuff fixed for VS2013

- tz.cpp
Sometimes the /etc/localtime points to another symlink. So, using realpath to resolve the symlink. 
One caveat is realpath only stores up to PATH_MAX bytes. Is this a concern? If so we may end up implementing our own realpath with examining any part of the path is a symlink or not. 
THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, …
> resolve /etc/localtime with realpath

- chrono_io.h
- date.h
- islamic.h
- julian.h
- tz.cpp
- tz.h
- tz_private.h
Title says it all - no actual change in the code, just a few typo I caught in the comments
> Fixes minor typos in comments - no actual change to code

- ios.mm
Fix memory leaks for CoreFoundation objects and tzdata path
> Fix memory leaks, tzdata path

- compile_fail.sh
- test_fail.sh
but will return 1 in testing if they actually built
> Updated testing so that failures of the should fail tests will compile

- CMakeLists.txt
Also add -fPIC flag when compiling the shared version of the library.
> Add option to disable string_view

- test/date_test/multi_year_duration_addition.pass.cpp
To work this specific test require current implementation
strategy (template with unspecified argument).
> Implemented test for checking addition with classes converible to years/months

- include/date/date.h
> Sign conversion warning

- CMakeLists.txt
Rename target date_interface to interface and tz to timezone.
Export targets date::interface and date::timezone from cmake.
> Improve main CMake file

- .travis.yml
- README.md
Added some nice descriptions and clang 6 & 7
> Enhancements to initial travis-ci support

- CMakeLists.txt
- cmake/dateConfig.cmake
> Fix cmake install for 3.14 or earlier (3.7 min)

- CMakeLists.txt
> set cmake proj ver to 3.0:

- include/date/date.h
> Fix uninitialized values in date.h

- CMakeLists.txt
This now reflects the latest tagged version
> cmake: update project version

- include/date/iso_week.h
- test/iso_week/year.pass.cpp
Closes #784 
Not sure if you also want to update https://howardhinnant.github.io/date/iso_week.html#year or not
> Expose `iso_week::year::is_leap()`

- include/date/date.h
see: https://github.com/HowardHinnant/date/issues/750
> workaround for gcc bug 106757

- include/date/tz.h
> Add missing DATE_API

- CMakeLists.txt
should be done with the release
> Update project version

- include/date/date.h
> Remove deprecated whitespace for Clang 20.1.0

- CMakeLists.txt
> CMake: Fix Apple Mobile platforms detection
