- date.h
> prevent GCC warning/error when using -pedantic or -pedantic-errors flags

- tz.h
I believe move constructors and assignment operators added by ivanp2015 to be able to compile under VS2013 are flawed and need to be fixed (apart from name in Zone and zones in TZ_DB other members are not initialized correctly!).
> Fixes for move constructors and assignment operators added for VS2013

- test/tz_test/validate.cpp
- tz.cpp
This patch tries to make the mapping file parsing more flexible on Windows by opening it in text mode.
The thinking is this will allow crlf or lf line endings to be managed by the CRT which means when the file is pulled from github it should work "as is" either way.
It also fixes a bug where the line number for error reporting wasn't accounting for the copyright notice.
Finally the patch attempts to slightly formalize that a notice should exist and be at least 3 lines followed by a blank line. That should allow the app to diagnose if someone removes the copyright and stop the app from silently dropping the few lines of time zone data instead etc.
The patch also has a change to the tz test validate program so that it issues an error message when exceptions are thrown. Otherwise when …
> mapping file suggested changes.

- chrono_io.h
The implementation of these functions used the expression:
```c++
return {1, 'x'};
```
This call the initializer list constructor of basic_string, which lead
to two char strings.
This changes the expression to:
```c++
return {'x'};
```
> Fix c++11 msl and get_units overloads return expression

- date.h
Solution: 
- add missing locale (first parameter is always locale)
- add missing include to *sstream* since basic_ostringstream is incomplete
> Problem: date::format(..) doesn't compile

- date.h
Soiution: cast them to system_clock::duration for the function call *to_time_t*. This shouldn't do any harm since the fractions of the second are handled maually before...
> Problem: time_points with a finer resolution than system_clock::duration cannot be formated

- iso_week.h
On my Fedora 24 box, Clang 3.8 needs an additional include directive in order to compile all tests successfully.
> Clang on Fedora needs <climits> for the CHAR_BIT definition.

- tz.cpp
This is needed for std::tie. GCC and Clang are fine with it missing, but
my Visual Studio doesn't like it.
> Add missing #include <tuple> in tz.cpp

- tz.cpp
There is one std::cout output in tz.cpp for Windows to get the windowsZones.xml path. Remove it. 
THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON …
> Remove a leftover output to std::cout

- tz.cpp
The tzdata package on Ubuntu 16.04, maybe other distributions too, includes /usr/share/zoneinfo/leap-
seconds.list. This is not a TZif file, so it should be ignored.
> Also ignore leap-seconds.list

- tz.cpp
tz.cpp:1617:24: error: unused parameter 't' [-Werror,-Wunused-parameter]
maybe_reverse_bytes(T& t, std::false_type)
^
tz.cpp:2470:1: error: unused function 'get_version' [-Werror,-Wunused-function]
get_version()
^
tz.cpp: In lambda function:
tz.cpp:1922:84: error: declaration of ‘t’ shadows a previous local [-Werror=shadow]
[](const sys_seconds& x, const transition& t)
^
tz.cpp:1921:19: note: shadowed declaration is here
for (auto t = std::upper_bound(transitions_.begin(), transitions_.end(), l,
^
> Fix compilation warnings for -DUSE_OS_TZDB.

- tz.h
(Upfront note: This patch will prevent some clients from linking to TZ as a shared library.
Those clients experiencing that will need to add the DATE_USED_SHARED=1 macro.
It's expected those clients will be relatively few compared to the statically linked users of TZ who should be able to remove the DATE_USE_LIB=1 macro from their project. Affects windows only currently.)
The existing formulation of macros for using tz as a static library or shared library is arguably not ideal.
Reasoning:
If you take use 3 from the USE CASE examples below, i.e. the 'compiling a client against the tz code as source code -the classic "drop tz into my project and go" path' one, using *the current* formulation of macros (i..e. before this patch), you will notice that you get different results on Linux from …
> Reformulate macros for static and shared linking on windows.

- src/tz.cpp
Windows header files (like **Windows.h**) suffer from inconsistent naming due to case insensitive Windows file access API. There is no difference on Windows, but MinGW implementation have lower case names (**windows.h**), and that matters in cross compilation scenarios. By proposing this change I assume nobody cross compiles on Linux with native Windows headers.
> Convert Windows header file names to lower case

- include/date/date.h
tm variable is not initialized in to_stream(), and valgrind warns about
"Conditional jump or move depends on uninitialised value(s)".
Initialize tm to zero, and with that done, we can drop tm
initializations from two particular code paths.
> Fix uninitialized variable use in to_stream()

- include/date/date.h
All the calls to `std::time_get::get` had `0` as end-of-range iterator.
E.g.
```
auto& f = use_facet<time_get<CharT>>(is.getloc());
// ...
f.get(is, 0, is, err, &tm, command, fmt+1);
```
Using `nullptr` instead of `0` doesn't trigger the GCC 5.x warning:
> warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
> Replacing 0 with nullptr to avoid GCC warning

- include/date/tz_private.h
This is a fix for build error on ubuntu 16.04 with gcc 5.4 in case when os provided timezone database is used. See issue #205 for details.
> Add a workaround for a missing operator<< for gcc 5 on linux.

- include/date/date.h
- src/tz.cpp
A few small patches that fix some errors / warnings when compiling on Windows with Visual Studio 2015 and the following clang toolsets:
- v140_clang_c2 toolset (MS version of clang 3.8.0)
- LLVM-vs2014 toolset ( LLVM Windows version of clang 5.0)
> patches to build on Windows with clang in MSVC

- CMakeLists.txt
- compile_fail.sh
- test_fail.sh
The pass tests work like any other cmake test
The fail tests currently do not work on win32 as they would need some script support
I have tested on clang/gcc under Ubuntu
I left the fail errors displayed on the fail tests
> Added testing to cmake

- CMakeLists.txt
include_directories() should not be used in modern cmake.
prefer target_xxx commands.
> cmake: use target_include_directories instead of include_directories

- src/tz.cpp
The directory detection code for Mac introduced in 22a229af9106c032949f9a87a9a4fd9cc667a1ee makes us crash on iOS - this fixes the iOS version.
Note that we can't check #ifdef TARGET_OS_IPHONE here but have to do #if TARGET_OS_IPHONE because on Mac this value is defined and set to 0.
> Fix iOS build

- CMakeLists.txt
To have a nicer CMake experience, some cmake-variable "pollution" (introduced by me -- sorry), can be improved:
Cmake-variables that have global visibility, but are **only** relevant within function `print_option` are now marked as advanced.
Thus the following CMake-variables are now marked as advanced, and only visible in `cmake-gui`, if "advanced" is clicked:
```cmake
PRINT_OPTION_CURR_BUILD_TZ_STATIC
PRINT_OPTION_CURR_USE_SYSTEM_TZ_DB
PRINT_OPTION_CURR_USE_TZ_DB_IN_DOT
```
Normally "advanced" is not clicked, and you then you'll have a nice short listing, where the above-mentioned variables are not shown (their only relevant to internal "bookkeeping" of function `print_option`).
> rename and mark-as-advanced cmake-variable used in print_option function

- CMakeLists.txt
Changed cmake to default to c++17 unless TZ_CXX_STANDARD is set(e.g. to 11,14 or 17)
> Set standard or default to C++17

- include/date/tz.h
With MSVC 2017 (15.6 Preview 2) they bumped the compiler version to 1913 but did not fix the underlying issue which our ifdef tries to workaround. I will check again when 15.6 is released, but wanted to give a heads up that we might need to bump the ifdef version we check on.
> bump msvc define to fix compile issue on MSVC 15.6

- include/date/ios.h
- src/tz.cpp
Use native system call to retrieve current zone info.
> implement current_zone() for iOS using native API from iOSUtils

- include/date/date.h
I'm introducing the date library to a legacy codebase. It has defined `string` class (other than `std::string`) in a global scope, making the date header to fail to compile.
The following:
```
struct string {}; 
#include <date/date.h>
``` 
fails to compile VS 2017.5 with `error C2872: 'string': ambiguous symbol`.
I fixed that by explicitly qualifing the `std::string` usage with `std` namespace. 
I see there are other symbols which might suffer from the same issue (like `numpunct`) but for now I fixed the one that stopped me from using the library.
> Fix VS compilation when there is a `string` type in the global scope

- CMakeLists.txt
There were a couple of features of the CMake build system in `date` that can be easily replaced with more "CMakey" `CMake`. There are more things to do but these ones seemed to be very clean mappings.
Feel free to reject this for backwards compat reasons (people would have to change the options they use with CMake).
> Standardise CMake files (BUILD_SHARED_LIBS and CMAKE_CXX_STANDARD)

- include/date/date.h
Parsing of dates in format "2018-05-25T09:22:38.684811653Z" is broken. This date is parsed to 1805429794651672965 nanoseconds which is equivalent to GMT: Friday, March 19, 2027 4:16:34 AM
Reference code:
std::string strDate = "2018-05-25T09:22:38.684811653Z";
std::istringstream in{ strDate };
date::sys_time<std::chrono::nanoseconds> tp;
in >> date::parse("%FT%TZ", tp);
> Eliminate use of uninitialized offset.

- include/date/date.h
- src/tz.cpp
1. seems that VS2017 is not so good in constexpr evaluation inside 'noexcept(<expr>) '
2. WinRT restricts access to filesystem, but with minor modification library can use tzdata packaged inside WinRT application
> fixed build with latest VS2017 (v15.7.1); also made usable in WinRT mode, where some file IO API are not available

- include/date/date.h
Full disclosure: I'm not that confident in my change, as I never really worked with those functions (especially I've no idea what happens if use wide chars as inputs?).
http://en.cppreference.com/w/cpp/string/byte/isspace says:
> the behavior of std::isspace is undefined if the argument's value is neither representable as unsigned char nor equal to EOF. To use these functions safely with plain chars (or signed chars), the argument should first be converted to unsigned char
I noticed this when using from_stream with a format string which contained utf8 characters under VisualStudio2017 which raised a debug assertion.
> isspace, isalnum are undefined for signed chars?

- test/clock_cast_test/local_t.pass.cpp
It was pointed out by my work colleague that use of numbers padded with zeros is a bad style - they are interpreted as octal literals, and works correctly (gives correct value), unless someone will want to configure September or 9th.
This only affects local_t test, that I have recently added.
> Remove usage of octal literals in tests

- include/date/date.h
- test/date_test/durations_output.pass.cpp
Changes the suffix used to days duration to single "d" instead of "[86400]s".
Updated test cases.
> Suffix d for days duration

- include/date/date.h
Latest and greatest MSVC (15.7.4, cl.exe version 19.14.26431) is not able to parse date.h with pretty unhelpful error:
```
include\date\date.h(7856): error C2059: syntax error: '}'
include\date\date.h(7856): note: see reference to class template instantiation 'date::detail::string_literal<CharT,N>' being compiled
include\date\date.h(151): note: see reference to class template instantiation 'std::chrono::duration<int,std::ratio<86400,1>>' being compiled
include\date\date.h(7758): fatal error C1075: '{': no matching token found
```
The problem is actually this line:
```
template <class U = CharT,
class = typename std::enable_if<1 < sizeof(U)>::type>
```
I am not an C++ standard expert but, MSVC (at lease in my opinion) incorrectly interprets <
Workaround is to parenthesize the operator (at …
> Workaround MSVC 19.14.26431 parsing bug

- test/clock_cast_test/custom_clock.pass.cpp
- test/clock_cast_test/local_t.pass.cpp
- test/clock_cast_test/noncastable.pass.cpp
- test/clock_cast_test/to_sys_return_utc_time.fail.cpp
- test/tz_test/zone.pass.cpp
I have noticed that I missed the license information in the recently added local_t.pass.cpp test file, which may lead to problems with library usage (at least for this test).
I have added missing license information, updated years in other tests. and also fixed missed license in the test/tz_test/zone.pass.cpp file (took info about dates and author from git log).
> Added missing license to unit test files

- date.html
Better explain that `from_stream` does not change the value of the target in case of an error and that `!ok()` is not an indication of error.
Fixes issue #387.
> Better explain that from_stream does not change the value of the target

- include/date/date.h
- include/date/tz.h
'using namespace std;' in header files can conflict with custom
namespace names. For example 'string' is used without 'std::'
qualification in tz.h. If tz.h is included in a file where string is a
namespace, it cannot be compiled anymore.
This is the case in my program where I put anything related to strings inside namespace string.
This fixes only the issue with string but I think other using namespace should be removed from all .h to avoid any bad surprises.
> Prefer using std::string that using namespace std and unqualified string

- src/tz.cpp
Hi Howard
Thanks for this great library!
When loading tzdb files on Linux 2 additional files are considered to be time zones.  And when enumerating time zones they are listed as valid time zones. This patch just skips them.
Kind regards,
Albert
> Ignore tzdata.zi and leapseconds tzdb files on Linux when loading time zones

- include/date/date.h
- c_encoding satisfies ctime wday encoding: days since Sunday, range
[0,6]
- iso_encoding satisfies ISO 8601 weekday:
a digit d from 1 through 7, beginning with Monday and ending with Sunday
in reference to: https://github.com/HowardHinnant/date/issues/378
> add c_encoding and iso_encoding weekday functions

- src/tz.cpp
VS2019 correctly points out that a conversion from a wide NTCS to std::string requires narrowing. This may result in an undesired string value. Implement the string conversion properly.
Signed-off-by: Daniela Engert <dani@ngrt.de>
> Fix problem with wchar_t* to std::string conversion.

- test/date_test/year_month.pass.cpp
Included set of unit test for year_month arithemtic with !ok() values, as they semantic is fully specified in standard.
> Unit tests for !year_month::ok() arithmetic.

- src/tz.cpp
Clang 9 (in Visual Studio) complains about a mixed signed-unsigned comparison and an unused function.
- Replace the naked `int` constant -1 by `std::size_t(-1)` with the same codegen as before (no curlies to avoid narrowing).
- Guard the definition of `get_download_folder()` by the same condition as its call-site.
Signed-off-by: Daniela Engert <dani@ngrt.de>
> Fix warnings from Clang

- src/tz.cpp
Fix for problem described in https://github.com/HowardHinnant/date/issues/446
It seems that unicode.org have moved windowsZones.xml to github.
This fix changes the download url to the 'raw' version of the file at github.
> Fix for Download of windowsZones.xml fails due to http 302

- include/date/date.h
Thanks for fixing the depreciation warning. 
Looks like there is a typo though ~~
> #endf -> #endif after recent change

- include/date/date.h
This is done to make the result of calling day() on
year_month_day_last object that is !ok() unspecified.
Checked only months, are there are needed to avoid UB.
> Removed undefined behavioir from year_mont_day_last::day

- test/date_test/parse.pass.cpp
Adding a source code comment to hint that the error is well known is a great idea.
This is what was suggested in https://github.com/HowardHinnant/date/issues/388#issuecomment-421677760
> #388 add comment on unit test failure

- include/date/tz.h
- test/tz_test/OffsetZone.h
- test/tz_test/OffsetZone.pass.cpp
- test/tz_test/zoned_time_deduction.pass.cpp
This implements a bunch of test for the zoned_time deduction guides.
This test showed up that a few fixes are necessary:
1) `string_view` constructor still produces better candidates, so the resolution is not reduced
2) we mishandle types that are convertible to `string_view` only as rvalue (suggested by Tim Song)
> Test and fixes for zoned_time deduction guides

- CMakeLists.txt
In my initial PR, I've set version to 1.0.0 cause was not sure which one is right now correct. But you already merged it, so I'm adding this small fix to sett version to the last release you have.
> set library version to 2.4.1

- .travis.yml
- CMakeLists.txt
- README.md
The first approximation of build matrix for date library. For now, It includes only Linux targets.  
On those targets, build goes fine:
```
Ubuntu 16.04 with gcc 7
Ubuntu 16.04 with gcc 8
Ubuntu 16.04 with gcc 9   
Ubuntu 18.04 with gcc 7
Ubuntu 18.05 with clang 6
```
I've checked on a couple of others. For example, with gcc 4 to 6, there are issues. Also with macOS targets. 
The question is what minimal amount of configurations we need for testing? I mean what operating systems and compiler versions.
> Enable CI build 

- CMakeLists.txt
When I use date inside a dynamic library I don't want to export date functions as part of my API so I set default visibility to hidden. This change makes date build honor this setting.
> Honor symbol visibility settings

- include/date/date.h
This only happened on VS2017/VS2015 because it uses int for minutes and hours but long long for milliseconds. On Linux, they are all int64_t
if h_ is std::numeric_limits<int>::max, i.e. 2147483648, while m_ and s_ are all 0. 
h_ + m_ overflows. 
THE FOLLOWING DISCLAIMER APPLIES TO ALL SOFTWARE CODE AND OTHER MATERIALS CONTRIBUTED IN CONNECTION WITH THIS SOFTWARE:
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES …
> change the order in hh_mm_ss::to_duration() to have correct result on Windows for cases when h is 2147483647 hours and m and s are all 0

- CMakeLists.txt
USE_AUTOLOAD wasn't used anywhere else in date's sources. AUTO_DOWNLOAD
is used in .cpp/.h files while never mentioned in CMakeLists.txt.
Must have been a typo.
> Fixed a typo in CMakeLists.txt: USE_AUTOLOAD => AUTO_DOWNLOAD

- CMakeLists.txt
Fixes #589.
The issue with the old code here is that the expansion of the cmake generator expression is that it doesn't resolve to `0` or `1` straight away, as would be needed.
> fix ONLY_C_LOCALE export from cmake

- README.md
The official Kotlin library for handling dates and times is out, and for *nix targets, it uses your library.
As the programmer that was tasked with implementing that library for all supported platforms other than Java and JavaScript, I want to personally thank you for your work: as can be seen here https://github.com/Kotlin/kotlinx-datetime/tree/master/core/nativeMain/cinterop/cpp, the code for *nix (in `cdate.cpp`) is the most succinct, readable and straightforward. Compared to Darwin and WinAPI (with both of which I also had to work as part of this endeavor), you really nailed the interface so that even our non-typical requirements were easily fulfilled!
> Add Kotlin's datetime library to the list of projects using this

- src/tz.cpp
Header include should follow the same preprocessor rules as function definition.
> Proposed fix for issue #161

- CMakeLists.txt
Commit 48f1455 dropped handling DISABLE_STRING_VIEW. This PR put it back as well as setting HAS_DEDUCTION_GUIDES which requires string view as well.
> Put back handling DISABLE_STRING_VIEW

- include/date/date.h
Closes #647 
As discussed in #647, the docs for `toupper()` recommend casting to `unsigned char` before calling it. Any input not representable as an `unsigned char` results in undefined behavior.
> Cast to `unsigned char` before calling `toupper()`

- src/tz.cpp
Curl resources are leaked without this
> Add global cleanup to curl object destructor

- README.md
- The instructions to build the library using CMAKE are wrong. It is necessary to add these flags or it will not recognize the `testit` target in the build time.
> Add flags in README to compile using cmake

- .gitattributes
- .gitignore
- include/date/ios.h
- include/date/julian.h
- include/date/solar_hijri.h
- src/ios.mm
- test/date_test/detail/decimal_format_seconds.pass.cpp
- test/date_test/multi_year_duration_addition.pass.cpp
- test/date_test/year_month.pass.cpp
- test/posix/ptz.pass.cpp
- test/tz_test/zoned_time.pass.cpp
- test/tz_test/zoned_time_deduction.pass.cpp
This PR mainly removes trailing whitespace. Trailing whitespace does nothing except take up disk space, so it should be removed.
I also added a `.gitattributes` file with a line that tells Git to automatically fix line ending problems. All of the files in this repo already have correct line endings, but this file will prevent the problem from ever occurring in the future.
> Remove trailing whitespace and add gitattributes

- include/date/date.h
This PR is a fix for #676.
Every call to `from_stream` in `date.h` is changed to explicitly use the version from the `date` namespace
> call from_stream explicitly from date namespace to avoide mix up with C++20 std::chrono::from_stream

- include/date/date.h
That happen because `sizeof(long long unsigned int) == sizeof(long double)` in 32-bit architectures.
> static_cast to silent warning implict conversion

- test/testit
Fixes https://github.com/HowardHinnant/date/issues/713
> test: use -pthread when $CXX is g++

- include/date/tz.h
- src/tz.cpp
A user pointed out in https://github.com/r-lib/tzdb/pull/19 that two signatures are out of sync (and apparently _only_ these two, according to their build tools). This PR just syncs them back up.
I chose to go with `install` here, as that seemed more informative.
https://github.com/HowardHinnant/date/blob/3776e0f18562b8813a8733aed3677e01e960a5a2/include/date/tz.h#L1300
https://github.com/HowardHinnant/date/blob/3776e0f18562b8813a8733aed3677e01e960a5a2/src/tz.cpp#L418
I chose to go with `tz_int` here, because in the implementation you perform a static cast of this `int tz_int` object to a `tz timezone` and that "real" `tz` object feels like it should have the better name.
https://github.com/HowardHinnant/date/blob/3776e0f18562b8813a8733aed3677e01e960a5a2/include/date/tz.h#L848 …
> Sync implementation and header signatures

- src/tz.cpp
When define MISSING_LEAP_SECONDS throws compile time `error: 'load_just_leaps' was not declared in this scope`
when find_read_and_leap_seconds tries to call load_just_leaps which surrounded with #if !MISSING_LEAP_SECONDS 
This commit surrounds call to load_just_leaps
> Fix compilation when MISSING_LEAP_SECONDS is set to true

- src/tz.cpp
Hello.
In Android, the timezone is not stored in **/etc/localtime** or any other file. We have to look for the value of the system property **persist.sys.timezone** instead.
This PR add this check for Android in `current_zone()` function.
> Support Android for get current_zone()

- src/tz.cpp
date's internal init_tzdb function iterates through the files provided by the tz database, and init_tzdb contains a list of files that should not be interpreted as being in TZif format.
The 2023d release of the tz database added a new file that is not in TZif format, zonenow.tab. However, this file had not been added to the ignore list.
This caused date to intepret the zonenow.tab file as a TZif file, which caused assertions to fire in debug mode if the user attempted to load its associated time_zone, causing load_header() to be invoked on the file, which would find that it did not contain a 'TZif' magic number.
This commit addresses the issue by adding the file to the ignore list.
The announcement on the tz database mailing list which describes the addition of zonenow.tab can be found at …
> Support tz databases from release 2023d and newer by adding new zonenow.tab file to ignore list

- .gitattributes
Fixes #815. I can still unzip the files then. (The extracted text file has Unix EOL conventions.)
> Update gitattributes of zip files to binary

- chrono_io.html
- d0355r7.html
- date.html
- islamic.html
- iso_week.html
- julian.html
- tz.html
This patch updates the html documentation to add the color-scheme meta element, signalling light and dark color scheme support, and updating the inline CSS styles to override some colors when dark mode is active, to make sure that the document is always readable.
I've also cleaned up a bit the CSS styles, but without functional changes.
I've only updated the latest standard revision (r7), but please let me know if I should revert changes to that file.
Here's how it looks on my system; the dark scheme is provided by the browser:
PS: to be clear, the page is rendered in dark mode only if the user has set dark mode in the browser/system settings
> docs: support dark color-scheme

- CMakeLists.txt
If the library gets compiled with `HAS_STRING_VIEW=1`, consumers always need to link to the functions using `std::string_view`, as they are the only ones compiled into the shared library.
If the library gets compiled with e.g. C++17 and the user uses an older standard version they'll still get an error, but an helpful compile-time one suggesting to enable C++17 mode, instead of a cryptic linking error.
You can find a longer explanation here: <https://github.com/HowardHinnant/date/pull/754#issuecomment-1361248007>
> build(cmake): always mark HAS_STRING_VIEW as part of the interface

- CMakeLists.txt
This gives user control over which folder header should be installed to instead of using hardcoded value `include/`. Variable `CMAKE_INSTALL_INCLUDEDIR` is provided after a call to `include(GNUInstallDirs)`
More info can be found about usage in docs: https://cmake.org/cmake/help/latest/command/install.html
This PR basically replace all `$<INSTALL_INTERFACE:include>` with `$<INSTALL_INTERFACE:include>`.
---
It was already correctly used here: 
https://github.com/HowardHinnant/date/blob/22ceabf205d8d678710a43154da5a06b701c5830/CMakeLists.txt#L173
here: https://github.com/HowardHinnant/date/blob/22ceabf205d8d678710a43154da5a06b701c5830/CMakeLists.txt#L178
and here: https://github.com/HowardHinnant/date/blob/22ceabf205d8d678710a43154da5a06b701c5830/CMakeLists.txt#L184
---
This fix a bug if …
> build: use standard `CMAKE_INSTALL_INCLUDEDIR` for header install folder

- CMakeLists.txt
When using `date` as a PRIVATE dependency, it is not required to install it. This flag give user using `date` with add_subdirectory the opportunity to disable install target Default behavior is conserved since ENABLE_DATE_INSTALL is ON
fix #751
> build: introduce `ENABLE_DATE_INSTALL` to allow user opt-out of install

- src/tz.cpp
`PATH_MAX` isn't guaranteed to be defined in Posix environments; it is only on systems that have a path length limit, and even in environments where it is defined its usage can lead to issues.
To avoid using `PATH_MAX`, I've made two main changes:
- Where `realpath()` was used, I've changed the code to use its [POSIX.1-2008](https://pubs.opengroup.org/onlinepubs/9699919799/functions/realpath.html)'s new behaviour, where passing a null pointer as the `resolved_name` buffer results in `realpath()` to automatically allocate a buffer large enough to handle the given path, that is returned to the caller. This has been supported for a long time as a GNU libc extension before being standardized.
- Where `readlink()` was used, the size of the buffer was already determined when calling `lstat()`; …
> Stop using PATH_MAX

- include/date/tz.h
- src/tz.cpp
This patch implements native tzdata parser for Android. This allows developers to re-use built-in Android tzdata without the need to ship and update IANA TZ data.
> Implement USE_OS_TZDB for Android

- include/date/tz.h
- src/tz.cpp
1. Code under #ifdef WINRT uses convert_utf8_to_utf16() function too, so this func should not be defined under #ifndef WINRT
2. Android has no curl.h, wordexp.h and even tz database is in non-standard binary format, but library still could be used on Android with user supplied tz database, if some defines are set to more reasonable defaults.
> Fixed build for WinRT and Android

- src/tz.cpp
The layout for timezones, on these targets, is
`/usr/share/zoneinfo/posix/Europe/Paris` instead of `/usr/share/zoneinfo/Europe/Paris`.
`/usr/share/zoneinfo/Europe/Paris` exists and is a symlink to `/usr/share/zoneinfo/posix/Europe/Paris`.
`/etc/localtime` correctly links to `/usr/share/zoneinfo/Europe/Paris`, so `readlink` must be used instead of `realpath`.
> Fix current_zone not working on buildroot+glibc target - refs #846

- test_fail.sh
The first change is a bugfix -- bash is not available on any system and the path to it is not always the same.
Calling `/usr/bin/env bash` is a good fix for that, but the script is not using any bash-specific stuff so I have made it call `/bin/sh` which is a standard location for the POSIX sh.
In the second commit I have simplified the code while keeping the functionality:
```console
$ ./test_fail.sh true && echo ok || echo bad
true
ok
$ ./test_fail.sh false && echo ok || echo bad
false
bad
```
> improve `test_fail.sh`

- test/solar_hijri_test/parse.pass.cpp
This fixes the warning (on amd64):
```
parse.pass.cpp:218:22: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
218 |   for (auto i = 0; i < sizeof(ymdd)/sizeof(ymdd[0]); ++i)
|                    ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> test/solar_hijri_test/parse.pass.cpp: specify unsigned type in loop

- include/date/islamic.h
- include/date/iso_week.h
- include/date/julian.h
- include/date/solar_hijri.h
As just discussed in [a comment at the recently merged #869](https://github.com/HowardHinnant/date/pull/869#issuecomment-2702513324), the same issue is present in a few more places.  This simple PR tries to get these remaining instances.
> Address remaining 'whitespace in literal' upsetting clang++-20

- include/date/date.h
- test/date_test/parse.pass.cpp
Closes https://github.com/HowardHinnant/date/issues/872
I've swapped out `rs` for `ru` everywhere I mentioned in #872 except for in `%C` where apparently century can be meaningfully negative. (Normally I'd wait for you to comment before doing a PR but it seemed like a POC was an easier way to see if I was missing anything with my idea)
I also went ahead and added some extra tests related to this. The majority of the new tests would not have passed before this change (meaning they would have previously performed a successful parse in some weird cases).
The test for a negative year in `%c` failing is dependent on the decision of #871, but reflects the current state of things.
> Use `ru{}` in favor of `rs{}` where it makes sense

- include/date/date.h
I happened to notice that if you try to parse something horrible like this
```
1970-01-01T00:00:00-a5:00[America/New_York]
```
(note the `a` in the time zone offset)
with this format string: `"%Y-%m-%dT%H:%M:%S%Ez[%Z]"`,
then you can end up with undefined behavior when parsing the `%z` bit.
- The `-` is handled up front, setting `neg = true`
- The `a` prevents `read()` from succeeding, so `toff` is never updated
- Since `neg = true`, `toff = -toff` is called.
This combination poses a problem because:
```
toff = not_a_offset = minutes::min() = long min
```
And due to two's complement, calling `-` on this minimum value is undefined behavior.
The easy solution seems to be to just not update `toff` if you know you're already in a fail state, this seems consistent with what `read_signed()` …
> Don't negate `toff` if we've already failed

- src/tz.cpp
If a line only contains tabs the word will be an empty string. And then is_prefix_of does match on rule, beacuse it's substring of length 0 is also an empty string. Subsequently the parsing of the rule fails with an exception.
> Don't fail on nearly blank lines

- include/date/date.h
a little change to support c++11 but GCC < 5, such as centos7.9 gcc4.8.5
> compatible for c++11 but GCC <
